--- @class Colorscheme
--- @field black string
--- @field red string
--- @field green string
--- @field yellow string
--- @field blue string
--- @field magenta string
--- @field cyan string
--- @field white string
--- @field brightblack string
--- @field brightred string
--- @field brightgreen string
--- @field brightyellow string
--- @field brightblue string
--- @field brightmagenta string
--- @field brightcyan string
--- @field brightwhite string
--- @field background string
--- @field grey string
--- @field dark string

--- @class Color
--- @field colorscheme string colorscheme to set
--- @field plugin? string plugin to highlight

--- @class Highlight
--- @field setup fun(opts: Color): nil configures highlighting
