--- @type table<string, string> -- commonly used icons
return {
  -- general
  bell = ' ',
  branch = '',
  checkmark = '✔',
  cmd_hist = '',
  cursor = '󰆾',
  dotted_circle = '󱥸 ',
  down = '',
  download = ' ',
  file = '',
  folder = '',
  fuzzy = '',
  gear = '',
  git = '',
  log = '',
  modified = '●',
  recent = '',
  search = '',
  status = '󰦒',
  up = '',
  vim = '',

  -- devicons
  javascript = '󰌞',
  typescript = '󰛦',
  lock = '',
  robot = '󱙺',

  -- lsp completions
  namespace = '󰌗',
  text = '󰉿',
  method = '󰆧',
  ['function'] = '󰆧',
  constructor = '',
  field = '',
  variable = '󰀫',
  class = '󰠱',
  interface = '',
  module = '',
  property = '󰜢',
  unit = '󰑭',
  value = '󰎠',
  enum = '',
  keyword = '󰌋',
  key = '',
  snippet = '',
  color = '󰏘',
  reference = '󰈇',
  enumMember = '',
  constant = '󰏿',
  struct = '󰙅',
  event = '',
  operator = '󰆕',
  typeparameter = '󰊄',
  table = '',
  object = '󰅩',
  tag = '',
  array = '[]',
  boolean = '',
  number = '',
  null = '󰟢',
  supermaven = '',
  string = '󰉿',
  calendar = '',
  watch = '󰥔',
  package = '',
  markdown = '',
  copilot = '',
  codeium = '',
  tabnine = '',
  bladenav = '',
  makefile = '',
  shell = '',
  sync = '',
  star = '',
  lightbulb = '󰌶',
  cloud = '',
  help = '󰋖',
}
