local icons = require 'ui.icons'
local thm = require('ui.highlights').palette

require('nvim-web-devicons').setup {
  override = {
    -- Defaults we lean on
    ['sh'] = { icon = icons.shell, name = 'sh' },
    ['bash'] = { icon = icons.shell, name = 'bash' },
    ['zsh'] = { icon = icons.shell, name = 'zsh' },
    ['default_icon'] = { icon = icons.file, name = 'Default' },
    ['js'] = { icon = icons.javascript, name = 'js' },
    ['ts'] = { icon = icons.typescript, name = 'ts' },
    ['lua'] = { icon = icons.lua, name = 'lua', color = thm.brightwhite },
    ['py'] = { icon = icons.python, name = 'py', color = thm.brightwhite },
    ['lock'] = { icon = icons.lock, name = 'lock' },
    ['.gitignore'] = { icon = icons.branch, name = 'git', color = thm.black },
    ['.cz.toml'] = { icon = icons.branch, name = '.cz.toml', color = thm.black },
    ['Makefile'] = { icon = icons.makefile, name = 'Makefile' },
    ['txt'] = { icon = icons.file, name = 'txt' },
    ['config'] = { icon = icons.gear, name = 'config', color = thm.magenta },
    ['md'] = { icon = icons.markdown, name = 'md', color = thm.brightyellow },

    -- Zsh helpers (autoload + wrappers)
    ['aliases'] = { icon = icons.command, name = 'aliases' },
    ['cheatsheet'] = { icon = icons.command, name = 'cheatsheet' },
    ['edit-all'] = { icon = icons.command, name = 'edit-all' },
    ['fix-tmux-remotes'] = { icon = icons.command, name = 'fix-tmux-remotes' },
    ['list-256'] = { icon = icons.command, name = 'list-256' },
    ['list-colors'] = { icon = icons.command, name = 'list-colors' },
    ['take'] = { icon = icons.command, name = 'take' },
    ['update-all'] = { icon = icons.command, name = 'update-all' },
    ['update-icons'] = { icon = icons.command, name = 'update-icons' },
    ['uvi'] = { icon = icons.command, name = 'uvi' },
    ['work'] = { icon = icons.command, name = 'work' },

    -- Dotfiles + environment helpers
    ['.dircolors'] = { icon = icons.gear, name = '.dircolors', color = thm.magenta },
    ['.hushlogin'] = { icon = icons.file, name = '.hushlogin', color = thm.brightblack },
    ['.python-version'] = { icon = icons.gear, name = '.python-version', color = thm.black },
    ['.ruff.toml'] = { icon = icons.gear, name = '.ruff.toml', color = thm.black },
    ['config.sh'] = { icon = icons.shell, name = 'config.sh' },
    ['fzf.sh'] = { icon = icons.shell, name = 'fzf.sh', color = thm.magenta },
    ['.bashrc'] = { icon = icons.shell, name = '.bashrc', color = thm.magenta },
    ['.bash_profile'] = { icon = icons.shell, name = '.bash_profile', color = thm.magenta },
    ['.blerc'] = { icon = icons.shell, name = 'Blerc', color = thm.magenta },
    ['.zshenv'] = { icon = icons.key, name = '.zshenv', color = thm.brightred },
    ['.zshrc'] = { icon = icons.shell, name = '.zshrc', color = thm.magenta },
    ['.zprofile'] = { icon = icons.shell, name = '.zprofile', color = thm.magenta },
    ['.p10k.zsh'] = { icon = icons.shell, name = '.p10k.zsh', color = thm.magenta },
    ['.env'] = { icon = icons.key, name = '.env', color = thm.brightred },
    ['env'] = { icon = icons.key, name = 'Env', color = thm.brightred },
    ['sourdiesel'] = { icon = icons.color, name = 'Sourdiesel', color = thm.cyan },
    ['sourdiesel.json'] = { icon = icons.color, name = 'SourdieselJson', color = thm.cyan },
    ['sourdiesel.lua'] = { icon = icons.color, name = 'SourdieselLua', color = thm.cyan },
    ['sourdiesel.toml'] = { icon = icons.color, name = 'SourdieselToml', color = thm.cyan },
    ['sourdiesel.terminal'] = { icon = icons.color, name = 'SourdieselTerminal', color = thm.cyan },
    ['theme.yml'] = { icon = icons.color, name = 'theme.yml', color = thm.cyan },
    ['.sqlite'] = { icon = icons.database, name = '.sqlite', color = thm.cyan },
    ['.sqlite-shm'] = { icon = icons.database, name = '.sqlite-shm', color = thm.cyan },
    ['.sqlite-wal'] = { icon = icons.database, name = '.sqlite-wal', color = thm.cyan },
    ['session.vim'] = { icon = icons.vim, name = 'Session.vim', color = thm.brightblack },
    ['bootstrap.sh'] = { icon = icons.sync, name = 'bootstrap.sh', color = thm.brightgreen },
    ['.state.itermexport'] = { icon = icons.gear, name = '.state.itermexport', color = thm.black },
    ['.localized'] = { icon = icons.file, name = '.localized', color = thm.brightblack },
    ['.dbxignore'] = { icon = icons.file, name = '.dbxignore' },
    ['.DS_Store'] = { icon = icons.macos, name = '.DS_Store', color = thm.brightblack },
    ['icon\r'] = { icon = icons.file, name = 'Icon', color = thm.brightblack },
    ['.bash_history'] = { icon = icons.log, name = '.bash_history', color = thm.red },
    ['.histfile'] = { icon = icons.log, name = '.histfile', color = thm.red },
    ['.history'] = { icon = icons.log, name = '.history', color = thm.red },
    ['.zsh_history'] = { icon = icons.log, name = '.zsh_history', color = thm.red },
    ['history.jsonl'] = { icon = icons.log, name = 'history.jsonl', color = thm.red },
    ['allowed_signers'] = { icon = icons.signature, name = 'allowed_signers', color = thm.brightblue },
    ['known_hosts'] = { icon = icons.host, name = 'known_hosts', color = thm.brightblue },
    ['.luarc.json'] = { icon = icons.gear, name = '.luarc.json', color = thm.black },
    ['.netrwhist'] = { icon = icons.netrwhist, name = '.netrwhist', color = thm.brightblack },
    ['.stylua.toml'] = { icon = icons.gear, name = '.stylua.toml', color = thm.black },
    ['main.shada'] = { icon = icons.vim, name = 'main.shada', color = thm.brightblack },
    ['agent.toml'] = { icon = icons.gear, name = 'agent.toml', color = thm.magenta },
    ['btop.conf'] = { icon = icons.gear, name = 'btop.conf', color = thm.magenta },
    ['btop.log'] = { icon = icons.log, name = 'btop.log', color = thm.red },
    ['config.yml'] = { icon = icons.gear, name = 'config.yml', color = thm.magenta },
    ['config.toml'] = { icon = icons.gear, name = 'config.toml', color = thm.magenta },
    ['extensions.json'] = { icon = icons.gear, name = 'extensions.json', color = thm.magenta },
    ['glow.yml'] = { icon = icons.gear, name = 'glow.yml', color = thm.magenta },
    ['hist'] = { icon = icons.log, name = 'hist', color = thm.red },
    ['histfile'] = { icon = icons.log, name = 'histfile', color = thm.red },
    ['history'] = { icon = icons.log, name = 'history', color = thm.red },
    ['lesshst'] = { icon = icons.log, name = 'lesshst', color = thm.red },
    ['session_index.jsonl'] = { icon = icons.gear, name = 'session_index.jsonl', color = thm.black },
    ['init.lua'] = { icon = icons.lua, name = 'init.lua', color = thm.magenta },
    ['karabiner.json'] = { icon = icons.gear, name = 'karabiner.json', color = thm.magenta },
    ['settings.json'] = { icon = icons.gear, name = 'settings.json', color = thm.magenta },
    ['starship.toml'] = { icon = icons.gear, name = 'starship.toml', color = thm.magenta },
    ['wezterm.lua'] = { icon = icons.lua, name = 'wezterm.lua', color = thm.magenta },
    ['AGENTS.md'] = { icon = icons.robot, name = 'AGENTS', color = thm.brightyellow },
    ['CLAUDE.md'] = { icon = icons.robot, name = 'CLAUDE', color = thm.brightyellow },
    ['README.md'] = { icon = icons.markdown, name = 'README', color = thm.brightyellow },
    ['LICENSE'] = { icon = icons.markdown, name = 'LICENSE', color = thm.brightyellow },
    ['CONTRIBUTING.md'] = { icon = icons.markdown, name = 'CONTRIBUTING', color = thm.brightyellow },
    ['SECURITY.md'] = { icon = icons.markdown, name = 'SECURITY', color = thm.brightyellow },

    -- Generic config formats
    ['conf'] = { icon = icons.gear, name = 'conf', color = thm.black },
    ['dat'] = { icon = icons.file, name = 'dat', color = thm.brightblack },
    ['json'] = { icon = icons.gear, name = 'json', color = thm.black },
    ['jsonc'] = { icon = icons.gear, name = 'jsonc', color = thm.black },
    ['jsonl'] = { icon = icons.gear, name = 'jsonl', color = thm.black },
    ['log'] = { icon = icons.log, name = 'log', color = thm.red },
    ['shada'] = { icon = icons.vim, name = 'shada', color = thm.brightblack },
    ['sqlite'] = { icon = icons.database, name = 'sqlite', color = thm.cyan },
    ['sqlite3'] = { icon = icons.database, name = 'sqlite3', color = thm.cyan },
    ['sqlite-shm'] = { icon = icons.database, name = 'sqlite-shm', color = thm.cyan },
    ['sqlite-wal'] = { icon = icons.database, name = 'sqlite-wal', color = thm.cyan },
    ['terminal'] = { icon = icons.color, name = 'terminal', color = thm.cyan },
    ['toml'] = { icon = icons.gear, name = 'toml', color = thm.black },
    ['tmtheme'] = { icon = icons.color, name = 'tmTheme', color = thm.cyan },
    ['tmux.conf'] = { icon = icons.gear, name = 'tmux.conf', color = thm.magenta },
    ['theme'] = { icon = icons.color, name = 'theme', color = thm.cyan },
    ['sublime-syntax'] = { icon = icons.syntax, name = 'sublime-syntax', color = thm.brightblue },
    ['yaml'] = { icon = icons.gear, name = 'yaml', color = thm.black },
    ['yml'] = { icon = icons.gear, name = 'yml', color = thm.black },
    ['xml'] = { icon = icons.gear, name = 'xml', color = thm.black },

    -- Package / lock manifests
    ['apt-packages.txt'] = { icon = icons.package, name = 'apt-packages', color = thm.brightmagenta },
    ['Brewfile'] = { icon = icons.package, name = 'Brewfile', color = thm.brightmagenta },
    ['Brewfile.lock.json'] = { icon = icons.package, name = 'Brewfile.lock', color = thm.brightmagenta },
    ['dnf-packages.txt'] = { icon = icons.package, name = 'dnf-packages', color = thm.brightmagenta },
    ['package.lock'] = { icon = icons.package, name = 'package.lock', color = thm.brightmagenta },
    ['package-lock.json'] = { icon = icons.package, name = 'package-lock', color = thm.brightmagenta },
    ['pnpm-lock.yaml'] = { icon = icons.package, name = 'pnpm-lock', color = thm.brightmagenta },
    ['yarn.lock'] = { icon = icons.package, name = 'yarn.lock', color = thm.brightmagenta },
    ['package.json'] = { icon = icons.package, name = 'package.json', color = thm.brightmagenta },
    ['bun.lockb'] = { icon = icons.package, name = 'bun.lockb', color = thm.brightmagenta },
    ['uv.lock'] = { icon = icons.package, name = 'uv.lock', color = thm.brightmagenta },
    ['requirements.txt'] = { icon = icons.package, name = 'requirements', color = thm.brightmagenta },
    ['poetry.lock'] = { icon = icons.package, name = 'poetry.lock', color = thm.brightmagenta },
    ['Pipfile'] = { icon = icons.package, name = 'Pipfile', color = thm.brightmagenta },
    ['Pipfile.lock'] = { icon = icons.package, name = 'Pipfile.lock', color = thm.brightmagenta },
    ['pyproject.toml'] = { icon = icons.package, name = 'pyproject', color = thm.brightmagenta },
    ['Cargo.toml'] = { icon = icons.package, name = 'Cargo.toml', color = thm.brightmagenta },
    ['Cargo.lock'] = { icon = icons.package, name = 'Cargo.lock', color = thm.brightmagenta },
    ['go.mod'] = { icon = icons.package, name = 'go.mod', color = thm.brightmagenta },
    ['go.sum'] = { icon = icons.package, name = 'go.sum', color = thm.brightmagenta },
    ['Gemfile'] = { icon = icons.package, name = 'Gemfile', color = thm.brightmagenta },
    ['Gemfile.lock'] = { icon = icons.package, name = 'Gemfile.lock', color = thm.brightmagenta },
    ['pom.xml'] = { icon = icons.package, name = 'pom.xml', color = thm.brightmagenta },
    ['build.gradle'] = { icon = icons.package, name = 'build.gradle', color = thm.brightmagenta },
    ['build.gradle.kts'] = { icon = icons.package, name = 'build.gradle.kts', color = thm.brightmagenta },
    ['gradle.lockfile'] = { icon = icons.package, name = 'gradle.lockfile', color = thm.brightmagenta },
    ['composer.json'] = { icon = icons.package, name = 'composer.json', color = thm.brightmagenta },
    ['composer.lock'] = { icon = icons.package, name = 'composer.lock', color = thm.brightmagenta },
    ['mix.exs'] = { icon = icons.package, name = 'mix.exs', color = thm.brightmagenta },
    ['mix.lock'] = { icon = icons.package, name = 'mix.lock', color = thm.brightmagenta },
    ['stack.yaml'] = { icon = icons.package, name = 'stack.yaml', color = thm.brightmagenta },
    ['cabal.project'] = { icon = icons.package, name = 'cabal.project', color = thm.brightmagenta },
    ['cabal.project.freeze'] = { icon = icons.package, name = 'cabal.project.freeze', color = thm.brightmagenta },
    ['pubspec.yaml'] = { icon = icons.package, name = 'pubspec.yaml', color = thm.brightmagenta },
    ['pubspec.lock'] = { icon = icons.package, name = 'pubspec.lock', color = thm.brightmagenta },
    ['Package.swift'] = { icon = icons.package, name = 'Package.swift', color = thm.brightmagenta },
    ['Package.resolved'] = { icon = icons.package, name = 'Package.resolved', color = thm.brightmagenta },
    ['packages.config'] = { icon = icons.package, name = 'packages.config', color = thm.brightmagenta },
    ['project.assets.json'] = { icon = icons.package, name = 'project.assets', color = thm.brightmagenta },
    ['nvim-pack-lock.json'] = { icon = icons.package, name = 'nvim-pack-lock', color = thm.brightmagenta },

    -- Temporary ShaDa files
    ['main.shada.tmp.a'] = { icon = icons.vim, name = 'main.shada.tmp.a', color = thm.brightblack },
    ['main.shada.tmp.b'] = { icon = icons.vim, name = 'main.shada.tmp.b', color = thm.brightblack },
    ['main.shada.tmp.c'] = { icon = icons.vim, name = 'main.shada.tmp.c', color = thm.brightblack },
    ['main.shada.tmp.d'] = { icon = icons.vim, name = 'main.shada.tmp.d', color = thm.brightblack },
    ['main.shada.tmp.e'] = { icon = icons.vim, name = 'main.shada.tmp.e', color = thm.brightblack },
    ['main.shada.tmp.f'] = { icon = icons.vim, name = 'main.shada.tmp.f', color = thm.brightblack },
    ['main.shada.tmp.g'] = { icon = icons.vim, name = 'main.shada.tmp.g', color = thm.brightblack },
    ['main.shada.tmp.h'] = { icon = icons.vim, name = 'main.shada.tmp.h', color = thm.brightblack },
    ['main.shada.tmp.i'] = { icon = icons.vim, name = 'main.shada.tmp.i', color = thm.brightblack },
    ['main.shada.tmp.j'] = { icon = icons.vim, name = 'main.shada.tmp.j', color = thm.brightblack },
    ['main.shada.tmp.k'] = { icon = icons.vim, name = 'main.shada.tmp.k', color = thm.brightblack },
    ['main.shada.tmp.l'] = { icon = icons.vim, name = 'main.shada.tmp.l', color = thm.brightblack },
    ['main.shada.tmp.m'] = { icon = icons.vim, name = 'main.shada.tmp.m', color = thm.brightblack },
    ['main.shada.tmp.n'] = { icon = icons.vim, name = 'main.shada.tmp.n', color = thm.brightblack },
    ['main.shada.tmp.o'] = { icon = icons.vim, name = 'main.shada.tmp.o', color = thm.brightblack },
    ['main.shada.tmp.p'] = { icon = icons.vim, name = 'main.shada.tmp.p', color = thm.brightblack },
    ['main.shada.tmp.q'] = { icon = icons.vim, name = 'main.shada.tmp.q', color = thm.brightblack },
    ['main.shada.tmp.r'] = { icon = icons.vim, name = 'main.shada.tmp.r', color = thm.brightblack },
    ['main.shada.tmp.s'] = { icon = icons.vim, name = 'main.shada.tmp.s', color = thm.brightblack },
    ['main.shada.tmp.t'] = { icon = icons.vim, name = 'main.shada.tmp.t', color = thm.brightblack },
    ['main.shada.tmp.u'] = { icon = icons.vim, name = 'main.shada.tmp.u', color = thm.brightblack },
    ['main.shada.tmp.v'] = { icon = icons.vim, name = 'main.shada.tmp.v', color = thm.brightblack },
    ['main.shada.tmp.w'] = { icon = icons.vim, name = 'main.shada.tmp.w', color = thm.brightblack },
    ['main.shada.tmp.x'] = { icon = icons.vim, name = 'main.shada.tmp.x', color = thm.brightblack },
    ['main.shada.tmp.y'] = { icon = icons.vim, name = 'main.shada.tmp.y', color = thm.brightblack },
    ['main.shada.tmp.z'] = { icon = icons.vim, name = 'main.shada.tmp.z', color = thm.brightblack },
  },
}
