local icons = require 'ui.icons'
local thm = require('ui.highlights').palette

local devicons_config = {
  override = {
    -- Defaults we lean on
    ['sh'] = { icon = icons.shell, name = 'sh', color = thm.white },
    ['bash'] = { icon = icons.shell, name = 'bash' },
    ['zsh'] = { icon = icons.shell, name = 'zsh' },
    -- nvim-web-devicons handles file icons only; directory glyphs live in tree.lua.
    ['default_icon'] = { icon = icons.file, name = 'Default' },
    ['js'] = { icon = icons.javascript, name = 'js', color = thm.white },
    ['ts'] = { icon = icons.typescript, name = 'ts', color = thm.white },
    ['tsx'] = { icon = icons.tsx, name = 'tsx', color = thm.white },
    ['css'] = { icon = icons.css, name = 'css', color = thm.white },
    ['html'] = { icon = icons.html, name = 'html', color = thm.white },
    ['lua'] = { icon = icons.lua, name = 'SourdieselLuaGeneric', color = thm.brightwhite },
    ['py'] = { icon = icons.python, name = 'py', color = thm.brightwhite },
    ['rs'] = { icon = icons.rust, name = 'SourdieselRust', color = thm.white },
    ['vim'] = { icon = icons.vim, name = 'vim', color = thm.white },
    ['lock'] = { icon = icons.lock, name = 'lock' },
    ['patch'] = { icon = icons.patch, name = 'Patch', color = thm.brightred },
    ['.gitignore'] = { icon = icons.branch, name = 'GitIgnore', color = thm.black },
    ['.gitkeep'] = { icon = icons.branch, name = 'GitKeep', color = thm.brightblack },
    ['Makefile'] = { icon = icons.makefile, name = 'Makefile' },
    ['txt'] = { icon = icons.textlines, name = 'txt', color = thm.black },
    ['config'] = { icon = icons.gear, name = 'config', color = thm.magenta },
    ['md'] = { icon = icons.markdown, name = 'md', color = thm.brightyellow },

    -- Keep common project config special-cases aligned with eva extension rules.
    ['eslint.config.js'] = { icon = icons.javascript, name = 'eslint.config.js', color = thm.white },
    ['vite.config.js'] = { icon = icons.javascript, name = 'vite.config.js', color = thm.white },
    ['vite.config.ts'] = { icon = icons.typescript, name = 'vite.config.ts', color = thm.white },
    ['test.js'] = { icon = icons.javascript, name = 'test.js', color = thm.white },
    ['test.ts'] = { icon = icons.typescript, name = 'test.ts', color = thm.white },
    ['test.tsx'] = { icon = icons.tsx, name = 'test.tsx', color = thm.white },
    ['tsconfig.app.json'] = { icon = icons.gear, name = 'tsconfig.app.json', color = thm.black },
    ['tsconfig.json'] = { icon = icons.gear, name = 'tsconfig.json', color = thm.black },
    ['tsconfig.node.json'] = { icon = icons.gear, name = 'tsconfig.node.json', color = thm.black },

    -- Zsh helpers (autoload + wrappers)
    ['aliases'] = { icon = icons.shell, name = 'aliases', color = thm.white },
    ['profile'] = { icon = icons.shell, name = 'profile', color = thm.white },
    ['cheatsheet'] = { icon = icons.command, name = 'cheatsheet', color = thm.white },
    ['edit-all'] = { icon = icons.command, name = 'edit-all', color = thm.white },
    ['fix-tmux-remotes'] = { icon = icons.command, name = 'fix-tmux-remotes', color = thm.white },
    ['glg'] = { icon = icons.command, name = 'glg', color = thm.white },
    ['l'] = { icon = icons.command, name = 'l', color = thm.white },
    ['list-256'] = { icon = icons.command, name = 'list-256', color = thm.white },
    ['list-colors'] = { icon = icons.command, name = 'list-colors', color = thm.white },
    ['patch-zsh-autocomplete'] = { icon = icons.command, name = 'patch-zsh-autocomplete', color = thm.white },
    ['t'] = { icon = icons.command, name = 't', color = thm.white },
    ['take'] = { icon = icons.command, name = 'take', color = thm.white },
    ['interactive'] = { icon = icons.shell, name = 'interactive', color = thm.white },
    ['toggle-tmux-client'] = { icon = icons.command, name = 'toggle-tmux-client', color = thm.white },
    ['update-tools'] = { icon = icons.command, name = 'update-tools', color = thm.white },
    ['update-icons'] = { icon = icons.command, name = 'update-icons', color = thm.white },
    ['uvi'] = { icon = icons.command, name = 'uvi', color = thm.white },

    -- Shell completions
    ['_cmp-compat.bash'] = { icon = icons.lightbulb, name = '_cmp-compat.bash', color = thm.brightcyan },
    ['atuin.bash'] = { icon = icons.lightbulb, name = 'atuin.bash', color = thm.brightcyan },
    ['bat.bash'] = { icon = icons.lightbulb, name = 'bat.bash', color = thm.brightcyan },
    ['bob.bash'] = { icon = icons.lightbulb, name = 'bob.bash', color = thm.brightcyan },
    ['cargo.bash'] = { icon = icons.lightbulb, name = 'cargo.bash', color = thm.brightcyan },
    ['claude.bash'] = { icon = icons.lightbulb, name = 'claude.bash', color = thm.brightcyan },
    ['dust.bash'] = { icon = icons.lightbulb, name = 'dust.bash', color = thm.brightcyan },
    ['eva.bash'] = { icon = icons.lightbulb, name = 'eva.bash', color = thm.brightcyan },
    ['fd.bash'] = { icon = icons.lightbulb, name = 'fd.bash', color = thm.brightcyan },
    ['herdr.bash'] = { icon = icons.lightbulb, name = 'herdr.bash', color = thm.brightcyan },
    ['hs.bash'] = { icon = icons.lightbulb, name = 'hs.bash', color = thm.brightcyan },
    ['pi.bash'] = { icon = icons.lightbulb, name = 'pi.bash', color = thm.brightcyan },
    ['rg.bash'] = { icon = icons.lightbulb, name = 'rg.bash', color = thm.brightcyan },
    ['starship.bash'] = { icon = icons.lightbulb, name = 'starship.bash', color = thm.brightcyan },
    ['tldr.bash'] = { icon = icons.lightbulb, name = 'tldr.bash', color = thm.brightcyan },
    ['update-tools.bash'] = { icon = icons.lightbulb, name = 'update-tools.bash', color = thm.brightcyan },
    ['uv.bash'] = { icon = icons.lightbulb, name = 'uv.bash', color = thm.brightcyan },
    ['_atuin'] = { icon = icons.lightbulb, name = '_atuin', color = thm.brightcyan },
    ['_bat'] = { icon = icons.lightbulb, name = '_bat', color = thm.brightcyan },
    ['_bob'] = { icon = icons.lightbulb, name = '_bob', color = thm.brightcyan },
    ['_cargo'] = { icon = icons.lightbulb, name = '_cargo', color = thm.brightcyan },
    ['_claude'] = { icon = icons.lightbulb, name = '_claude', color = thm.brightcyan },
    ['_dust'] = { icon = icons.lightbulb, name = '_dust', color = thm.brightcyan },
    ['_eva'] = { icon = icons.lightbulb, name = '_eva', color = thm.brightcyan },
    ['_fd'] = { icon = icons.lightbulb, name = '_fd', color = thm.brightcyan },
    ['_herdr'] = { icon = icons.lightbulb, name = '_herdr', color = thm.brightcyan },
    ['_hs'] = { icon = icons.lightbulb, name = '_hs', color = thm.brightcyan },
    ['_pi'] = { icon = icons.lightbulb, name = '_pi', color = thm.brightcyan },
    ['_rg'] = { icon = icons.lightbulb, name = '_rg', color = thm.brightcyan },
    ['_starship'] = { icon = icons.lightbulb, name = '_starship', color = thm.brightcyan },
    ['_tldr'] = { icon = icons.lightbulb, name = '_tldr', color = thm.brightcyan },
    ['_update-tools'] = { icon = icons.lightbulb, name = '_update-tools', color = thm.brightcyan },
    ['_uv'] = { icon = icons.lightbulb, name = '_uv', color = thm.brightcyan },
    ['_work'] = { icon = icons.lightbulb, name = '_work', color = thm.brightcyan },

    -- Dotfiles + environment helpers
    ['.editorconfig'] = { icon = icons.gear, name = '.editorconfig', color = thm.black },
    ['.gitattributes'] = { icon = icons.branch, name = '.gitattributes', color = thm.black },
    ['.hushlogin'] = { icon = icons.shell, name = '.hushlogin', color = thm.brightblack },
    ['index.html'] = { icon = icons.html, name = 'index.html', color = thm.magenta },
    ['.python-version'] = { icon = icons.gear, name = '.python-version', color = thm.black },
    ['.vale.ini'] = { icon = icons.gear, name = '.vale.ini', color = thm.black },
    ['config.sh'] = { icon = icons.shell, name = 'config.sh', color = thm.white },
    ['atuin-zsh-tty-capture.zsh'] = { icon = icons.shell, name = 'AtuinZshTtyCapture', color = thm.brightred },
    ['.bashrc'] = { icon = icons.shell, name = '.bashrc', color = thm.magenta },
    ['.bash_profile'] = { icon = icons.shell, name = '.bash_profile', color = thm.magenta },
    ['.blerc'] = { icon = icons.shell, name = 'Blerc', color = thm.magenta },
    ['.shellcheckrc'] = { icon = icons.gear, name = '.shellcheckrc', color = thm.black },
    ['.zshenv'] = { icon = icons.shell, name = '.zshenv', color = thm.magenta },
    ['.zshrc'] = { icon = icons.shell, name = '.zshrc', color = thm.magenta },
    ['.zprofile'] = { icon = icons.shell, name = '.zprofile', color = thm.magenta },
    ['.zstyle'] = { icon = icons.shell, name = '.zstyle', color = thm.white },
    ['.p10k.zsh'] = { icon = icons.shell, name = '.p10k.zsh', color = thm.magenta },
    ['.env'] = { icon = icons.key, name = '.env', color = thm.brightred },
    ['env'] = { icon = icons.key, name = 'env', color = thm.magenta },
    ['sourdiesel'] = { icon = icons.color, name = 'Sourdiesel', color = thm.cyan },
    ['sourdiesel.json'] = { icon = icons.color, name = 'SourdieselJson', color = thm.cyan },
    ['sourdiesel.lua'] = { icon = icons.color, name = 'SourdieselLua', color = thm.cyan },
    ['sourdiesel.toml'] = { icon = icons.color, name = 'SourdieselToml', color = thm.cyan },
    ['sourdiesel.terminal'] = { icon = icons.color, name = 'SourdieselTerminal', color = thm.cyan },
    ['theme.yml'] = { icon = icons.color, name = 'theme.yml', color = thm.cyan },
    ['sh.vim'] = { icon = icons.syntax, name = 'sh.vim', color = thm.brightblue },
    ['zsh.vim'] = { icon = icons.syntax, name = 'zsh.vim', color = thm.brightblue },
    ['typescriptreact.vim'] = { icon = icons.syntax, name = 'typescriptreact.vim', color = thm.brightblue },
    ['secrets'] = { icon = icons.socket, name = 'secrets', color = thm.cyan },
    ['.sqlite'] = { icon = icons.database, name = '.sqlite', color = thm.cyan },
    ['.sqlite-shm'] = { icon = icons.database, name = '.sqlite-shm', color = thm.cyan },
    ['.sqlite-wal'] = { icon = icons.database, name = '.sqlite-wal', color = thm.cyan },
    ['.sock'] = { icon = icons.socket, name = '.sock', color = thm.cyan },
    ['.socket'] = { icon = icons.socket, name = '.socket', color = thm.cyan },
    ['session.vim'] = { icon = icons.vim, name = 'Session.vim', color = thm.brightblack },
    ['.state.itermexport'] = { icon = icons.gear, name = '.state.itermexport', color = thm.black },
    ['.localized'] = { icon = icons.file, name = '.localized', color = thm.brightblack },
    ['.file'] = { icon = icons.file, name = 'SourdieselDotFile', color = thm.brightblack },
    ['.dbxignore'] = { icon = icons.file, name = '.dbxignore' },
    ['.dockerignore'] = { icon = icons.docker, name = '.dockerignore', color = thm.brightblue },
    ['.DS_Store'] = { icon = icons.macos, name = '.DS_Store', color = thm.brightblack },
    ['icon\r'] = { icon = icons.file, name = 'Icon', color = thm.brightblack },
    ['.bash_history'] = { icon = icons.log, name = '.bash_history', color = thm.red },
    ['.histfile'] = { icon = icons.log, name = '.histfile', color = thm.red },
    ['.history'] = { icon = icons.log, name = '.history', color = thm.red },
    ['.mycli_history'] = { icon = icons.log, name = '.mycli_history', color = thm.red },
    ['.mysql_history'] = { icon = icons.log, name = '.mysql_history', color = thm.red },
    ['.python_history'] = { icon = icons.log, name = '.python_history', color = thm.red },
    ['.zsh_history'] = { icon = icons.log, name = '.zsh_history', color = thm.red },
    ['history.jsonl'] = { icon = icons.log, name = 'history.jsonl', color = thm.red },
    ['allowed_signers'] = { icon = icons.signature, name = 'allowed_signers', color = thm.white },
    ['known_hosts'] = { icon = icons.host, name = 'known_hosts', color = thm.white },
    ['identity'] = { icon = icons.git, name = 'identity', color = thm.white },
    ['auth.key'] = { icon = icons.key, name = 'auth.key', color = thm.brightred },
    ['auth.key.pub'] = { icon = icons.key, name = 'auth.key.pub', color = thm.white },
    ['id_ed25519'] = { icon = icons.key, name = 'id_ed25519', color = thm.brightred },
    ['id_ed25519.pub'] = { icon = icons.key, name = 'id_ed25519.pub', color = thm.black },
    ['signing.key'] = { icon = icons.key, name = 'signing.key', color = thm.brightred },
    ['signing.key.pub'] = { icon = icons.key, name = 'signing.key.pub', color = thm.white },
    ['1password'] = { icon = icons.gear, name = '1password', color = thm.white },
    ['ssh-agent'] = { icon = icons.gear, name = 'ssh-agent', color = thm.white },
    ['.luarc.json'] = { icon = icons.gear, name = '.luarc.json', color = thm.black },
    ['.netrwhist'] = { icon = icons.netrwhist, name = '.netrwhist', color = thm.brightblack },
    ['CACHEDIR.TAG'] = { icon = icons.netrwhist, name = 'CACHEDIR.TAG', color = thm.red },
    ['_update-notifier-last-checked'] = { icon = icons.file, name = 'NpmUpdateNotifier', color = thm.black },
    ['main.shada'] = { icon = icons.vim, name = 'main.shada', color = thm.brightblack },
    ['main.py'] = { icon = icons.python, name = 'main.py', color = thm.magenta },
    ['vercel.json'] = { icon = icons.gear, name = 'vercel.json', color = thm.black },
    ['agent.toml'] = { icon = icons.gear, name = 'agent.toml', color = thm.magenta },
    ['btop.conf'] = { icon = icons.gear, name = 'btop.conf', color = thm.magenta },
    ['btop.log'] = { icon = icons.log, name = 'btop.log', color = thm.red },
    ['config.yml'] = { icon = icons.gear, name = 'config.yml', color = thm.magenta },
    ['config.toml'] = { icon = icons.gear, name = 'config.toml', color = thm.magenta },
    ['extensions.json'] = { icon = icons.gear, name = 'extensions.json', color = thm.magenta },
    ['glow.yml'] = { icon = icons.gear, name = 'glow.yml', color = thm.magenta },
    ['hist'] = { icon = icons.log, name = 'hist', color = thm.red },
    ['histfile'] = { icon = icons.log, name = 'histfile', color = thm.red },
    ['history'] = { icon = icons.log, name = 'history', color = thm.red },
    ['lesshst'] = { icon = icons.log, name = 'lesshst', color = thm.red },
    ['session_index.jsonl'] = { icon = icons.gear, name = 'session_index.jsonl', color = thm.black },
    ['init.lua'] = { icon = icons.lua, name = 'init.lua', color = thm.magenta },
    ['karabiner.json'] = { icon = icons.gear, name = 'karabiner.json', color = thm.magenta },
    ['matplotlibrc'] = { icon = icons.gear, name = 'MatplotlibConfig', color = thm.magenta },
    ['npmrc'] = { icon = icons.gear, name = 'NpmConfig', color = thm.magenta },
    ['settings.json'] = { icon = icons.gear, name = 'settings.json', color = thm.magenta },
    ['starship.toml'] = { icon = icons.gear, name = 'starship.toml', color = thm.magenta },
    ['wezterm.lua'] = { icon = icons.lua, name = 'wezterm.lua', color = thm.magenta },
    ['Containerfile'] = { icon = icons.docker, name = 'Containerfile', color = thm.brightblue },
    ['Dockerfile'] = { icon = icons.docker, name = 'SourdieselDockerfile', color = thm.brightblue },
    ['compose.yaml'] = { icon = icons.docker, name = 'compose.yaml', color = thm.brightblue },
    ['compose.yml'] = { icon = icons.docker, name = 'compose.yml', color = thm.brightblue },
    ['docker-compose.yaml'] = { icon = icons.docker, name = 'docker-compose.yaml', color = thm.brightblue },
    ['docker-compose.yml'] = { icon = icons.docker, name = 'docker-compose.yml', color = thm.brightblue },
    ['AGENTS.md'] = { icon = icons.robot, name = 'AGENTS', color = thm.brightyellow },
    ['CLAUDE.md'] = { icon = icons.robot, name = 'CLAUDE', color = thm.brightyellow },
    ['CODEOWNERS'] = { icon = icons.branch, name = 'CODEOWNERS', color = thm.black },
    ['README.md'] = { icon = icons.markdown, name = 'SourdieselREADME', color = thm.brightyellow },
    ['LICENSE'] = { icon = icons.license, name = 'SourdieselLicense', color = thm.brightyellow },
    ['CONTRIBUTING.md'] = { icon = icons.markdown, name = 'CONTRIBUTING', color = thm.brightyellow },
    ['SECURITY.md'] = { icon = icons.markdown, name = 'SourdieselSecurity', color = thm.brightyellow },

    -- Image formats
    ['avif'] = { icon = icons.image, name = 'SourdieselAvif', color = thm.cyan },
    ['gif'] = { icon = icons.image, name = 'SourdieselGif', color = thm.cyan },
    ['heic'] = { icon = icons.image, name = 'SourdieselHeic', color = thm.cyan },
    ['heif'] = { icon = icons.image, name = 'SourdieselHeif', color = thm.cyan },
    ['icns'] = { icon = icons.image, name = 'SourdieselIcns', color = thm.cyan },
    ['jpeg'] = { icon = icons.image, name = 'SourdieselJpeg', color = thm.cyan },
    ['jpg'] = { icon = icons.image, name = 'SourdieselJpg', color = thm.cyan },
    ['png'] = { icon = icons.image, name = 'SourdieselPng', color = thm.cyan },
    ['svg'] = { icon = icons.vector, name = 'SourdieselSvg', color = thm.cyan },
    ['webp'] = { icon = icons.image, name = 'SourdieselWebp', color = thm.cyan },

    -- Generic config formats
    ['conf'] = { icon = icons.gear, name = 'conf', color = thm.black },
    ['csv'] = { icon = icons.table, name = 'csv', color = thm.cyan },
    ['dat'] = { icon = icons.file, name = 'dat', color = thm.brightblack },
    ['ini'] = { icon = icons.gear, name = 'ini', color = thm.black },
    ['json'] = { icon = icons.gear, name = 'json', color = thm.black },
    ['jsonc'] = { icon = icons.gear, name = 'jsonc', color = thm.black },
    ['jsonl'] = { icon = icons.gear, name = 'jsonl', color = thm.black },
    ['log'] = { icon = icons.log, name = 'log', color = thm.red },
    ['shada'] = { icon = icons.vim, name = 'shada', color = thm.brightblack },
    ['scpt'] = { icon = icons.macos, name = 'scpt', color = thm.white },
    ['sqlite'] = { icon = icons.database, name = 'sqlite', color = thm.cyan },
    ['sqlite3'] = { icon = icons.database, name = 'sqlite3', color = thm.cyan },
    ['sqlite-shm'] = { icon = icons.database, name = 'sqlite-shm', color = thm.cyan },
    ['sqlite-wal'] = { icon = icons.database, name = 'sqlite-wal', color = thm.cyan },
    ['sock'] = { icon = icons.socket, name = 'sock', color = thm.cyan },
    ['socket'] = { icon = icons.socket, name = 'socket', color = thm.cyan },
    ['terminal'] = { icon = icons.color, name = 'terminal', color = thm.cyan },
    ['toml'] = { icon = icons.gear, name = 'toml', color = thm.black },
    ['tmtheme'] = { icon = icons.color, name = 'tmTheme', color = thm.cyan },
    ['tmux.conf'] = { icon = icons.gear, name = 'tmux.conf', color = thm.magenta },
    ['theme'] = { icon = icons.color, name = 'theme', color = thm.cyan },
    ['sublime-syntax'] = { icon = icons.syntax, name = 'sublime-syntax', color = thm.brightblue },
    ['yaml'] = { icon = icons.gear, name = 'yaml', color = thm.black },
    ['yml'] = { icon = icons.gear, name = 'yml', color = thm.black },
    ['xml'] = { icon = icons.gear, name = 'xml', color = thm.black },

    -- Package / lock manifests
    ['apt-packages.txt'] = { icon = icons.package, name = 'apt-packages', color = thm.brightmagenta },
    ['Brewfile'] = { icon = icons.package, name = 'Brewfile', color = thm.brightmagenta },
    ['Brewfile.1password'] = { icon = icons.package, name = 'Brewfile1Password', color = thm.brightmagenta },
    ['Brewfile.developer'] = { icon = icons.package, name = 'BrewfileDeveloper', color = thm.brightmagenta },
    ['Brewfile.lock.json'] = { icon = icons.package, name = 'BrewfileLock', color = thm.brightmagenta },
    ['Brewfile.personal'] = { icon = icons.package, name = 'BrewfilePersonal', color = thm.brightmagenta },
    ['Brewfile.rust'] = { icon = icons.package, name = 'BrewfileRust', color = thm.brightmagenta },
    ['dnf-packages.txt'] = { icon = icons.package, name = 'dnf-packages', color = thm.brightmagenta },
    ['package.lock'] = { icon = icons.package, name = 'package.lock', color = thm.brightmagenta },
    ['package-lock.json'] = { icon = icons.package, name = 'package-lock', color = thm.brightmagenta },
    ['pnpm-lock.yaml'] = { icon = icons.package, name = 'pnpm-lock', color = thm.brightmagenta },
    ['yarn.lock'] = { icon = icons.package, name = 'yarn.lock', color = thm.brightmagenta },
    ['package.json'] = { icon = icons.package, name = 'package.json', color = thm.brightmagenta },
    ['bun.lockb'] = { icon = icons.package, name = 'bun.lockb', color = thm.brightmagenta },
    ['uv.lock'] = { icon = icons.package, name = 'uv.lock', color = thm.brightmagenta },
    ['requirements.txt'] = { icon = icons.package, name = 'requirements', color = thm.brightmagenta },
    ['poetry.lock'] = { icon = icons.package, name = 'poetry.lock', color = thm.brightmagenta },
    ['Pipfile'] = { icon = icons.package, name = 'Pipfile', color = thm.brightmagenta },
    ['Pipfile.lock'] = { icon = icons.package, name = 'Pipfile.lock', color = thm.brightmagenta },
    ['pyproject.toml'] = { icon = icons.package, name = 'pyproject', color = thm.brightmagenta },
    ['Cargo.toml'] = { icon = icons.package, name = 'Cargo.toml', color = thm.brightmagenta },
    ['Cargo.lock'] = { icon = icons.package, name = 'Cargo.lock', color = thm.brightmagenta },
    ['go.mod'] = { icon = icons.package, name = 'go.mod', color = thm.brightmagenta },
    ['go.sum'] = { icon = icons.package, name = 'go.sum', color = thm.brightmagenta },
    ['Gemfile'] = { icon = icons.package, name = 'Gemfile', color = thm.brightmagenta },
    ['Gemfile.lock'] = { icon = icons.package, name = 'Gemfile.lock', color = thm.brightmagenta },
    ['pom.xml'] = { icon = icons.package, name = 'pom.xml', color = thm.brightmagenta },
    ['build.gradle'] = { icon = icons.package, name = 'build.gradle', color = thm.brightmagenta },
    ['build.gradle.kts'] = { icon = icons.package, name = 'build.gradle.kts', color = thm.brightmagenta },
    ['gradle.lockfile'] = { icon = icons.package, name = 'gradle.lockfile', color = thm.brightmagenta },
    ['composer.json'] = { icon = icons.package, name = 'composer.json', color = thm.brightmagenta },
    ['composer.lock'] = { icon = icons.package, name = 'composer.lock', color = thm.brightmagenta },
    ['mix.exs'] = { icon = icons.package, name = 'mix.exs', color = thm.brightmagenta },
    ['mix.lock'] = { icon = icons.package, name = 'mix.lock', color = thm.brightmagenta },
    ['stack.yaml'] = { icon = icons.package, name = 'stack.yaml', color = thm.brightmagenta },
    ['cabal.project'] = { icon = icons.package, name = 'cabal.project', color = thm.brightmagenta },
    ['cabal.project.freeze'] = { icon = icons.package, name = 'cabal.project.freeze', color = thm.brightmagenta },
    ['pubspec.yaml'] = { icon = icons.package, name = 'pubspec.yaml', color = thm.brightmagenta },
    ['pubspec.lock'] = { icon = icons.package, name = 'pubspec.lock', color = thm.brightmagenta },
    ['Package.swift'] = { icon = icons.package, name = 'Package.swift', color = thm.brightmagenta },
    ['Package.resolved'] = { icon = icons.package, name = 'Package.resolved', color = thm.brightmagenta },
    ['packages.config'] = { icon = icons.package, name = 'packages.config', color = thm.brightmagenta },
    ['project.assets.json'] = { icon = icons.package, name = 'project.assets', color = thm.brightmagenta },
    ['nvim-pack-lock.json'] = { icon = icons.package, name = 'nvim-pack-lock', color = thm.brightmagenta },

    -- Temporary ShaDa files
    ['main.shada.tmp.a'] = { icon = icons.vim, name = 'main.shada.tmp.a', color = thm.brightblack },
    ['main.shada.tmp.b'] = { icon = icons.vim, name = 'main.shada.tmp.b', color = thm.brightblack },
    ['main.shada.tmp.c'] = { icon = icons.vim, name = 'main.shada.tmp.c', color = thm.brightblack },
    ['main.shada.tmp.d'] = { icon = icons.vim, name = 'main.shada.tmp.d', color = thm.brightblack },
    ['main.shada.tmp.e'] = { icon = icons.vim, name = 'main.shada.tmp.e', color = thm.brightblack },
    ['main.shada.tmp.f'] = { icon = icons.vim, name = 'main.shada.tmp.f', color = thm.brightblack },
    ['main.shada.tmp.g'] = { icon = icons.vim, name = 'main.shada.tmp.g', color = thm.brightblack },
    ['main.shada.tmp.h'] = { icon = icons.vim, name = 'main.shada.tmp.h', color = thm.brightblack },
    ['main.shada.tmp.i'] = { icon = icons.vim, name = 'main.shada.tmp.i', color = thm.brightblack },
    ['main.shada.tmp.j'] = { icon = icons.vim, name = 'main.shada.tmp.j', color = thm.brightblack },
    ['main.shada.tmp.k'] = { icon = icons.vim, name = 'main.shada.tmp.k', color = thm.brightblack },
    ['main.shada.tmp.l'] = { icon = icons.vim, name = 'main.shada.tmp.l', color = thm.brightblack },
    ['main.shada.tmp.m'] = { icon = icons.vim, name = 'main.shada.tmp.m', color = thm.brightblack },
    ['main.shada.tmp.n'] = { icon = icons.vim, name = 'main.shada.tmp.n', color = thm.brightblack },
    ['main.shada.tmp.o'] = { icon = icons.vim, name = 'main.shada.tmp.o', color = thm.brightblack },
    ['main.shada.tmp.p'] = { icon = icons.vim, name = 'main.shada.tmp.p', color = thm.brightblack },
    ['main.shada.tmp.q'] = { icon = icons.vim, name = 'main.shada.tmp.q', color = thm.brightblack },
    ['main.shada.tmp.r'] = { icon = icons.vim, name = 'main.shada.tmp.r', color = thm.brightblack },
    ['main.shada.tmp.s'] = { icon = icons.vim, name = 'main.shada.tmp.s', color = thm.brightblack },
    ['main.shada.tmp.t'] = { icon = icons.vim, name = 'main.shada.tmp.t', color = thm.brightblack },
    ['main.shada.tmp.u'] = { icon = icons.vim, name = 'main.shada.tmp.u', color = thm.brightblack },
    ['main.shada.tmp.v'] = { icon = icons.vim, name = 'main.shada.tmp.v', color = thm.brightblack },
    ['main.shada.tmp.w'] = { icon = icons.vim, name = 'main.shada.tmp.w', color = thm.brightblack },
    ['main.shada.tmp.x'] = { icon = icons.vim, name = 'main.shada.tmp.x', color = thm.brightblack },
    ['main.shada.tmp.y'] = { icon = icons.vim, name = 'main.shada.tmp.y', color = thm.brightblack },
    ['main.shada.tmp.z'] = { icon = icons.vim, name = 'main.shada.tmp.z', color = thm.brightblack },
  },
}

devicons_config.override_by_filename = devicons_config.override
devicons_config.override_by_extension = devicons_config.override

require('nvim-web-devicons').setup(devicons_config)
