#!/usr/bin/env zsh

# Reload zsh
bindkey -s '^o' 'exec "$(brew --prefix)/bin/zsh"\n'

# Autosuggestions
bindkey '^e' autosuggest-accept

# Clear screen
bindkey -s '^[l' 'clear\n'

# Atuin search in vim mode
bindkey -M vicmd '^r' atuin-search
bindkey -M vicmd '^[[A' atuin-up-search
bindkey -M vicmd '^[OA' atuin-up-search
