#!/usr/bin/env zsh

alias gst='git status'
alias glg='git log --graph --date=format:"%b-%d-%Y" --pretty="%C(yellow)%h %C(magenta)%an %C(brightmagenta)%ad%C(auto)%d %C(white)%s %Creset"'
alias gss='git status --short'
alias grs='git restore'
alias grst='git restore --staged'
alias gcmsg='git commit --message'
alias gcam='git commit --all --message'
alias gcl='git clone --recurse-submodules'
alias gd='git diff'
alias gds='git diff --staged'
alias gp='git push'
alias gl='git pull'
alias gf='git fetch'
alias ga='git add'
alias gaa='git add --all'
alias grv='git remote --verbose'
alias gmv='git mv'
alias grm='git rm'
alias gco='git checkout'
alias gsw='git switch'
alias gb='git branch'
alias gmg='git merge'
alias gsa='git submodule add'
