#!/usr/bin/env zsh

command -v git &>/dev/null || {
  printf "${BRIGHTRED}%s %s${RESET}\n" "✘" "git unavailable or not in PATH"
  return 1
}

local plugin=''

for plugin in "$TMUX_PLUGIN_MANAGER_PATH"/*; do
  [[ -d "$plugin/.git" ]] || continue

  local name="${plugin:t}"
  local repo=tmux-plugins

  case $name in
  tmux-fzf) repo=sainnhe ;;
  tmux-fzf-url) repo=junegunn ;;
  tmux-mode-indicator) repo=MunifTanjim ;;
  vim-tmux-navigator) repo=christoomey ;;
  esac

  git -C "$plugin" remote set-url origin "git@github.com:$repo/$name.git"
  printf "${GREEN}%s  ${BLACK}Set remote for ${MAGENTA}%s ${WHITE}→ ${BLUE}%s${RESET}\n" "" "$name" "$repo/$name"
done
