#!/usr/bin/env zsh

for plugin in "$TMUX_PLUGIN_MANAGER_PATH"/*; do
  [[ -d "$plugin/.git" ]] || continue

  local name="${plugin:t}"
  local repo=tmux-plugins

  case $name in
  tmux-fzf) repo=sainnhe ;;
  tmux-fzf-url) repo=junegunn ;;
  tmux-mode-indicator) repo=MunifTanjim ;;
  vim-tmux-navigator) repo=christoomey ;;
  esac

  git -C "$plugin" remote set-url origin "git@github.com:$repo/$name.git"
  echo "${GREEN}  ${BLACK}Set remote for ${MAGENTA}$name ${WHITE}→ ${BLUE}$repo/$name${RESET}"
done
