#!/usr/bin/env zsh

for plugin in "$TMUX_PLUGIN_MANAGER_PATH"/*; do
  [[ -d "$plugin/.git" ]] || continue

  local name="${plugin:t}"

  case $name in
  tmux-fzf) local repo=sainnhe ;;
  tmux-fzf-url) local repo=junegunn ;;
  tmux-mode-indicator) local repo=MunifTanjim ;;
  vim-tmux-navigator) local repo=christoomey ;;
  *) local repo=tmux-plugins ;;
  esac

  git -C "$plugin" remote set-url origin "git@github.com:$repo/$name.git"
  echo "${GREEN}  ${BLACK}Set remote for ${MAGENTA}$name ${WHITE}→ ${BLUE}$repo/$name${RESET}"
done
