#!/usr/bin/env zsh

# Function overload for git switch fuzzy finding

if (( $# == 0 )) && command -v fzf; then
  git switch $(git branch | fzf --header 'Switch Local  ' \
                                --preview 'git show --color=always $(echo {} | awk "{print \$1}")'
  )
else
  git switch "$@"
fi
