#!/usr/bin/env zsh

local session
session=$(tmux list-sessions -F "#{session_name}" | fzf \
  --header="tmux switch/attach" \
  --border-label="  sessions " \
  --no-preview)

[[ -z $session ]] && return 0

[[ -n $TMUX ]] && tmux switch-client -t "$session" && exit
tmux attach-session -t "$session"
