#!/usr/bin/env zsh

local colors=(
  $BLACK_HEX
  $RED_HEX
  $GREEN_HEX
  $YELLOW_HEX
  $BLUE_HEX
  $MAGENTA_HEX
  $CYAN_HEX
  $WHITE_HEX
  $BRIGHTBLACK_HEX
  $BRIGHTRED_HEX
  $BRIGHTGREEN_HEX
  $BRIGHTYELLOW_HEX
  $BRIGHTBLUE_HEX
  $BRIGHTMAGENTA_HEX
  $BRIGHTCYAN_HEX
  $BRIGHTWHITE_HEX
)

for hex in "$colors[@]"; do
  # Convert hex to RGB
  local r=${hex[2,3]}; r=$((16#$r))
  local g=${hex[4,5]}; g=$((16#$g))
  local b=${hex[6,7]}; b=$((16#$b))

  # Create the ANSI escape sequence for the color
  local ansi="\e[38;2;${r};${g};${b}m"

  printf "${ansi}(%s) The quick brown fox jumps over the lazy dog${RESET}\n" "$hex"
done
