#!/usr/bin/env zsh

local session
session=$(tmux list-sessions -F "#{session_name}" | \
  fzf --header="tmux switch/attach" \
      --border-label="  sessions " \
      --preview='tmux list-windows -t {}' \
      --preview-window=up:wrap:60%)

[ -z "$session" ] && return 0

if [ -n "$TMUX" ]; then
  tmux switch-client -t "$session"
else
  tmux attach-session -t "$session"
fi
