#!/usr/bin/env zsh

local hex

local colors=(
  "$BLACK_HEX"
  "$RED_HEX"
  "$GREEN_HEX"
  "$YELLOW_HEX"
  "$BLUE_HEX"
  "$MAGENTA_HEX"
  "$CYAN_HEX"
  "$WHITE_HEX"
  "$BRIGHTBLACK_HEX"
  "$BRIGHTRED_HEX"
  "$BRIGHTGREEN_HEX"
  "$BRIGHTYELLOW_HEX"
  "$BRIGHTBLUE_HEX"
  "$BRIGHTMAGENTA_HEX"
  "$BRIGHTCYAN_HEX"
  "$BRIGHTWHITE_HEX"
)

for hex in "${colors[@]}"; do
  # Convert hex to RGB
  local r=$((16#${hex:1:2}))
  local g=$((16#${hex:3:2}))
  local b=$((16#${hex:5:2}))

  # Create the ANSI escape sequence for the color
  local ansi="\e[38;2;${r};${g};${b}m"

  printf "${ansi}(%s) The quick brown fox jumps over the lazy dog${RESET}\n" "$hex"
done
