#!/usr/bin/env zsh

local brewfile="${1:-$HOME/.dotfiles/Brewfile}"

# Run homebrew command and cask updates
brew upgrade
brew cu -af

# Run homebrew utilities
brew cleanup
brew doctor
brew bundle dump --force --file="$brewfile"

# Customize app icon for any upgraded cask
update-icons

# Update Tex Live Utility
# sudo tlmgr update --self --all
