#!/usr/bin/env zsh

local branches=("$@")

# Dynamically fetch feature branches if no arguments are provided
[[ $# -eq 0 ]] && branches=("${(@f)$(git branch --format='%(refname:short)' | grep '^feature/')}")

for branch in "${branches[@]}"; do
  # Check if branch exists
  git branch --format='%(refname:short)' | grep -Fxq "$branch" || { printf "${RED}  '%s' not found${RESET} - run ${GREEN}'git branch'${RESET} to show available branches\n" "$branch"; continue; }

  # Perfom merge
  git switch "$branch" &>/dev/null
  git merge main &>/dev/null

  # Print success message after switching
  printf "${GREEN}  ${RESET}${CYAN}%s${RESET} -> ${MAGENTA}main${RESET}\n" "$branch"
done
