#!/usr/bin/env zsh

# Check for 'fileicon' binary
command -v fileicon &>/dev/null || {
  printf "${BRIGHTRED}%s %s${BRIGHTYELLOW}%s${RESET}\n" "" "'fileicon' dependency not found" " - please install or check in \$PATH."
  return 1
}

table_width=60

# Directory - Icons
dir_icons=(
  "/Applications/1Password.app" "$HOME/Pictures/icons/1password-macos.png"
  "/Applications/ChatGPT.app" "$HOME/Pictures/icons/chatgpt.png"
  "/Applications/Discord.app" "$HOME/Pictures/icons/discord-macos.png"
  "/Applications/Dropbox.app" "$HOME/Pictures/icons/dropbox.png"
  "/Applications/Figma.app" "$HOME/Pictures/icons/figma.png"
  "/Applications/Firefox.app" "$HOME/Pictures/icons/firefox.png"
  "/Applications/Google Chrome.app" "$HOME/Pictures/icons/chrome.png"
  "/Applications/iTerm.app" "$HOME/Pictures/icons/iterm2.png"
  "/Applications/iTermAI.app" "$HOME/Pictures/icons/ai-brain.png"
  "/Applications/KeyCastr.app" "$HOME/Pictures/icons/keycastr.png"
  "/Applications/Neovim-iTerm.app" "$HOME/Pictures/icons/neovim-iterm.png"
  "/Applications/Neovim-Wezterm.app" "$HOME/Pictures/icons/neovim-wezterm.png"
  "/Applications/Postman.app" "$HOME/Pictures/icons/postman.png"
  "/Applications/Slack.app" "$HOME/Pictures/icons/slack.png"
  "/Applications/Spotify.app" "$HOME/Pictures/icons/spotify.png"
  "/Applications/Visual Studio Code.app" "$HOME/Pictures/icons/vscode.png"
  "/Applications/WezTerm.app" "$HOME/Pictures/icons/wezterm.png"
  "/Applications/WhatsApp.app" "$HOME/Pictures/icons/whatsapp.png"
  "$HOME/Developer" "$HOME/Pictures/icons/developer.png"
  "$HOME/Downloads" "$HOME/Pictures/icons/download.png"
  "$HOME/Dropbox/content" "$HOME/Pictures/icons/content.png"
  "$HOME/Pictures/icons" "$HOME/Pictures/icons/png.png"
  "$HOME/Pictures/screenshots" "$HOME/Pictures/icons/screenshot.png"
  "$HOME/Pictures/wallpapers" "$HOME/Pictures/icons/wallpaper.png"
  "$HOME/.dotfiles" "$HOME/Pictures/icons/gear.png"
)

print_separator() {
  printf "${BRIGHTBLACK}%-${table_width}s${RESET}\n" | tr ' ' '-'
}

# Create header
print_separator
printf "%-2s ${BLUE}%-37s ${MAGENTA}%-5s${RESET}\n" '' 'App / Directory' \~/Pictures/icons/
print_separator

# Create rows
local success=0 fail=0

for ((i = 1; i < ${#dir_icons[@]}; i += 2)); do
  dir="${dir_icons[i]}"
  icon="${dir_icons[i + 1]}"
  short_dir="${dir/#$HOME/~}"

  print_status() {
    printf "${1}%-1s ${WHITE}%-37s ${BRIGHTMAGENTA}%-5s${RESET}\n" "$2" "$short_dir" "$(basename "$icon")"
  }

  fileicon set "$dir" "$icon" &>/dev/null || {
    print_status "${RED}" " "
    ((fail++))
    continue
  }

  print_status "${GREEN}" " "
  ((success++))
done

# Create Footer
print_separator
printf "${GREEN}%-2s ${BRIGHTBLACK}%-37s${RESET}\n" "${success:-0}" 'Folder icon(s) updated successfully'
(($fail == 0)) || printf "${RED}%-2s ${BRIGHTBLACK}%-37s${RESET}\n" "$fail" 'Folder icon(s) failed to update'
