#!/usr/bin/env zsh

# Check for 'fileicon' binary
command -v fileicon &>/dev/null || {
  printf "${BRIGHTRED}%s %s${BRIGHTYELLOW}%s${RESET}\n" "✘" "'fileicon' dependency not found" " - please install or check in \$PATH."
  return 1
}

table_width=60

# Directory - Icons
dir_icons=(
  "/Applications/1Password.app" "$HOME/Pictures/icons/1password.png"
  "/Applications/Anki.app" "$HOME/Pictures/icons/anki.png"
  "/Applications/ChatGPT.app" "$HOME/Pictures/icons/chatgpt.png"
  "/Applications/Discord.app" "$HOME/Pictures/icons/discord.png"
  "/Applications/Figma.app" "$HOME/Pictures/icons/figma.png"
  "/Applications/Firefox.app" "$HOME/Pictures/icons/firefox.png"
  "/Applications/Hammerspoon.app" "$HOME/Pictures/icons/hammerspoon.png"
  "/Applications/iTerm.app" "$HOME/Pictures/icons/iterm2.png"
  "/Applications/iTermAI.app" "$HOME/Pictures/icons/ai-brain.png"
  "/Applications/KeyCastr.app" "$HOME/Pictures/icons/keycastr.png"
  "/Applications/Messenger.app" "$HOME/Pictures/icons/messenger.png"
  "/Applications/Neovim-iTerm.app" "$HOME/Pictures/icons/neovim-iterm.png"
  "/Applications/Neovim-Wezterm.app" "$HOME/Pictures/icons/neovim-wezterm.png"
  "/Applications/Notion Calendar.app" "$HOME/Pictures/icons/notion-calendar.png"
  "/Applications/Postman.app" "$HOME/Pictures/icons/postman.png"
  "/Applications/Skim.app" "$HOME/Pictures/icons/skim.png"
  "/Applications/Slack.app" "$HOME/Pictures/icons/slack.png"
  "/Applications/Spotify.app" "$HOME/Pictures/icons/spotify.png"
  "/Applications/Visual Studio Code.app" "$HOME/Pictures/icons/vscode.png"
  "/Applications/WeChat.app" "$HOME/Pictures/icons/wechat.png"
  "/Applications/WezTerm.app" "$HOME/Pictures/icons/wezterm.png"
  "/Applications/WhatsApp.app" "$HOME/Pictures/icons/whatsapp.png"
  "$HOME/Developer" "$HOME/Pictures/icons/developer.png"
  "$HOME/Downloads" "$HOME/Pictures/icons/download.png"
  "$HOME/Dropbox/content" "$HOME/Pictures/icons/content.png"
  "$HOME/Pictures/icons" "$HOME/Pictures/icons/png.png"
  "$HOME/Pictures/screenshots" "$HOME/Pictures/icons/screenshot.png"
  "$HOME/Pictures/wallpapers" "$HOME/Pictures/icons/wallpaper.png"
  "$HOME/.dotfiles" "$HOME/Pictures/icons/gear.png"
)

print_separator() {
  printf "${BRIGHTBLACK}%-${table_width}s${RESET}\n" | tr ' ' '-'
}

# Create header
print_separator
printf "%-2s ${BLUE}%-37s ${MAGENTA}%-5s${RESET}\n" '' 'App / Directory' \~/Pictures/icons/
print_separator

# Create rows
local success=0 fail=0

for ((i = 1; i < ${#dir_icons[@]}; i += 2)); do
  local dir="$dir_icons[i]"
  local icon="$dir_icons[i + 1]"

  print_status() {
    local highlight="${1}%-1s ${WHITE}%-37s ${BRIGHTMAGENTA}%-5s${RESET}"
    local status_icon="$2"

    printf "$highlight\n" "$status_icon" "${dir/#$HOME/~}" "${icon:t}"
  }

  fileicon set "$dir" "$icon" &>/dev/null || {
    print_status "$RED" "✘"
    ((fail++))
    continue
  }

  print_status "$GREEN" "✔"
  ((success++))
done

# Create Footer
print_separator
printf "${GREEN}%-2s ${BRIGHTBLACK}%-37s${RESET}\n" "$success" 'Folder icon(s) updated successfully'
(($fail == 0)) || printf "${RED}%-2s ${BRIGHTBLACK}%-37s${RESET}\n" "$fail" 'Folder icon(s) failed to update'
