#!/usr/bin/env zsh

# Ensure fileicon installed
command -v fileiconn || {
  echo 'fileicon not found'
  return 1
}

# Finder location: "/System/Library/CoreServices/Finder.app/Contents"
local src="/System/Applications/$1.app/Contents"
local tgt="$HOME/Applications/$1.app"

mkdir -p "$tgt"
ln -s "$src" "$tgt"
fileicon set "$tgt" "$HOME/Pictures/icons/$2.png"
