#!/bin/usr/env zsh

autoclose-symbol() { LBUFFER="${LBUFFER}$1"; CURSOR=$(( CURSOR - 1 )) }

autoclose-parenthesis() { autoclose-symbol "()" }
autoclose-bracket() { autoclose-symbol "[]" }
autoclose-brace() { autoclose-symbol "{}" }
autoclose-single-quote() { autoclose-symbol "''" }
autoclose-double-quote() { autoclose-symbol '""' }
autoclose-backtick() { autoclose-symbol '``' }

zle -N autoclose-parenthesis
zle -N autoclose-bracket
zle -N autoclose-brace
zle -N autoclose-single-quote
zle -N autoclose-double-quote
zle -N autoclose-backtick

bindkey '(' autoclose-parenthesis
bindkey '[' autoclose-bracket
bindkey '{' autoclose-brace
bindkey "'" autoclose-single-quote
bindkey '"' autoclose-double-quote
bindkey '`' autoclose-backtick
