#!/usr/bin/env zsh

zstyle ':completion:*:unambiguous' format \
  $'%{\e[0;2m%}%Bcommon substring:%b %{\e[0m%}%{\e[38;5;1m%}%d%{\e[0m%}'

zsh_completion_colors=(
  ${(s.:.)LS_COLORS}
  'ma=00;38;5;14'
)

zstyle ':completion:*:default' list-colors "${zsh_completion_colors[@]}"
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts \
  'reply=(${=${${(f)"$(cat /etc/ssh_hosts ~/.config/ssh/known_hosts 2>/dev/null)"}%%[# ]*}//,/ })'
