#!/usr/bin/env zsh

# File: update-branches

local branches=("$@")

# Default branches
[[ $# -eq 0 ]] && branches=(
  bootstrap
  fzf
  hammerspoon
  nvim
  shell
  tmux
  wezterm
)

for branch in "${branches[@]}"; do git switch "feature/$branch" && git merge main; done

git switch main

git log -5 --graph --date=format:"%b-%d-%Y" --pretty="%C(yellow)%h %C(blue)%an %C(brightmagenta)%ad%C(auto)%d %C(white)%s %Creset"
