#!/usr/bin/env zsh

# Upgrade all Homebrew packages
brew upgrade

# Update all casks (brew cu -af requires the brew-cask-upgrade plugin)
brew cu -af

# Cleanup outdated versions and temporary files
brew cleanup

# Run brew doctor to check for any potential issues
brew doctor

# Dump the current state of installed packages to a Brewfile
brew bundle dump --force --file="$DOT/.Brewfile"
