#!/usr/bin/env zsh

local usage='usage: l [eva-options] [paths...]'

[[ ${1:-} == '-h' || ${1:-} == '--help' ]] && printf '%s\n' "$usage" && return

command -v eva &>/dev/null || return 127
eva --all --long --git --icons=always --group-directories-first "$@"
