[tui]
session_picker_view = "comfortable"
status_line = ["thread-title", "model-with-reasoning", "current-dir", "context-remaining", "five-hour-limit", "weekly-limit", "run-state"]
status_line_use_colors = true

[desktop]
appearanceTheme = "dark"
appearanceDarkCodeThemeId = "catppuccin"
sansFontSize = 15
codeFontSize = 15
usePointerCursors = true
mac-menu-bar-enabled = false
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true

[desktop.appearanceDarkChromeTheme]
surface = "#212030"
ink = "#cccccc"
accent = "#eccef0"
contrast = 60
opaqueWindows = false

[desktop.appearanceDarkChromeTheme.fonts]
code = "JetBrainsMono NF ExtraLight"

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#ceffc9"
diffRemoved = "#ffc7c7"
skill = "#c9ccfb"

[desktop.open-in-target-preferences]
global = "iterm2"
