local b16 = require 'ui.base16'
require('ui.utils').highlight {

	Added = { fg = b16.green },
	Removed = { fg = b16.red },
	Changed = { fg = b16.yellow },
	MatchWord = { bg = b16.black, fg = b16.white },

	Pmenu = { bg = b16.one_bg },
	PmenuSbar = { bg = b16.one_bg },
	PmenuSel = { bg = b16.white, fg = b16.black },
	PmenuThumb = { bg = b16.black },

	MatchParen = { link = 'MatchWord' },
	Comment = { fg = b16.brightblack },
	CursorLineNr = { fg = b16.black },
	LineNr = { fg = b16.brightblack },
	FloatBorder = { fg = b16.blue },
	FloatTitle = { fg = b16.magenta },
	NormalFloat = { bg = b16.background },
	NvimInternalError = { fg = b16.red },
	WinSeparator = { fg = b16.brightblack },
	Normal = { fg = b16.white, bg = b16.background },
	DevIconDefault = { fg = b16.red },
	Debug = { fg = b16.white },
	Directory = { fg = b16.blue },
	Error = { fg = b16.black, bg = b16.white },
	ErrorMsg = { fg = b16.red, bg = b16.background },
	Exception = { fg = b16.brightred },
	FoldColumn = { bg = b16.background },
	Folded = { fg = b16.black, bg = b16.black },
	IncSearch = { fg = b16.black, bg = b16.orange },
	Macro = { fg = b16.white },
	ModeMsg = { fg = b16.green },
	MoreMsg = { fg = b16.green },
	Question = { fg = b16.blue },
	Search = { fg = b16.black, bg = b16.yellow },
	Substitute = { fg = b16.black, bg = b16.yellow },
	SpecialKey = { fg = b16.black },
	TooLong = { fg = b16.white },
	Visual = { bg = b16.black },
	VisualNOS = { fg = b16.white },
	WarningMsg = { fg = b16.white, bg = b16.background },
	WildMenu = { fg = b16.white, bg = b16.yellow },
	Title = { fg = b16.blue },
	Conceal = { bg = b16.background },
	Cursor = { fg = b16.black, bg = b16.white },
	NonText = { fg = b16.black },
	SignColumn = { fg = b16.black },
	ColorColumn = { bg = b16.black },
	CursorColumn = { bg = b16.black },
	CursorLine = { bg = b16.black },
	QuickFixLine = { fg = b16.brightred, bg = b16.background },
	healthSuccess = { bg = b16.green, fg = b16.black },
	WinBar = { bg = b16.background },
	WinBarNC = { bg = b16.background },

	NvDashAscii = { fg = b16.blue },
	NvDashButtons = { fg = b16.black }, -- grey to black
	NvDashFooter = { fg = b16.red },
}
