return {
  modified = '󰷬',

  -- virtual text
  virtualblock = '󱓻',
  virtualcircle = '',

  -- general
  gear = '',
  file = '',
  download = ' ',
  checkmark = ' ',
  dotted_circle = '󱥸 ',
  bell = ' ',

  -- lsp diagnostics
  error = '󰯈',
  warn = '',
  hint = '',
  info = '',

  -- devicons
  javascript = '󰌞',
  typescript = '󰛦',
  lock = '',
  robot = '󱙺',

  -- lsp completions
  completions = {
    Namespace = '󰌗',
    Text = '󰉿',
    Method = '󰆧',
    Function = '󰆧',
    Constructor = '',
    Field = '',
    Variable = '󰀫',
    Class = '󰠱',
    Interface = '',
    Module = '',
    Property = '󰜢',
    Unit = '󰑭',
    Value = '󰎠',
    Enum = '',
    Keyword = '󰌋',
    Snippet = '',
    Color = '󰏘',
    File = '',
    Reference = '󰈇',
    Folder = '',
    EnumMember = '',
    Constant = '󰏿',
    Struct = '󰙅',
    Event = '',
    Operator = '󰆕',
    TypeParameter = '󰊄',
    Table = '',
    Object = '󰅩',
    Tag = '',
    Array = '[]',
    Boolean = '',
    Number = '',
    Null = '󰟢',
    Supermaven = '',
    String = '󰉿',
    Calendar = '',
    Watch = '󰥔',
    Package = '',
    Copilot = '',
    Codeium = '',
    TabNine = '',
    BladeNav = '',
  },
}
