#!/usr/bin/env bash

# Editor
alias v='nvim'
alias va='nvim $(fd -HItf --exclude .git --exclude .github --exclude Session.vim)'
alias vf='fzf --preview "bat -n --color=always {}" | xargs -r "$EDITOR"'
alias vs='nvim -S Session.vim'
alias refresh-shada='mv -f "$XDG_STATE_HOME/nvim/shada/main.shada.tmp.x" "$XDG_STATE_HOME/nvim/shada/main.shada"'

alias vim='vim -i "$XDG_STATE_HOME/vim/viminfo"'
alias vi='vim'

# File Navigation & Previewing
alias -- -="cd -"
alias ~="cd $HOME"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

alias cl='clear'
alias grep='grep --color=auto'
alias l='eza --all --long --git --icons=always --group-directories-first'
alias tree='tree -aCI ".git|.github"'

# Printing Long List Format
alias list-aliases='alias | sort'
alias list-colors=list_colors
alias list-dependencies='brew deps --tree --installed'
alias list-env-vars='env | sort'
alias list-path='tr ":" "\n" <<< "$PATH"'
alias list-users='dscl . list /Users | grep -v "^_"'
alias list-shells='tail -n +5 /etc/shells'
alias list-sysinfo='system_profiler SPSoftwareDataType SPHardwareDataType'

# Update Management
alias update-brew='update_brew'
alias update-icons='update_icons'
alias update-texlive='update_texlive'
alias update-all='update_all'
alias update-feature-branches='update_feature_branches'

# Deletion
alias delete-ds-store='fd -HI .DS_Store / -x rm -f {} &>/dev/null'

# Tmux
alias t='tmux attach || tmux new-session'
alias ta='tmux attach -t'
alias tn='tmux new-session'
alias tks='tmux kill-server'
alias tl='tmux_list_sessions'

# Git
alias gst='git status'
alias glg='git log --graph --date=format:"%b-%d-%Y" --pretty="$GIT_PRETTY"'
alias gss='git status --short'
alias grs='git restore'
alias grst='git restore --staged'
alias gcmsg='git commit --message'
alias gcam='git commit --all --message'
alias gcl='git clone --recurse-submodules'
alias gd='git diff'
alias gds='git diff --staged'
alias gp='git push'
alias gl='git pull'
alias gf='git fetch'
alias ga='git add'
alias gaa='git add --all'
alias grv='git remote --verbose'
alias gmv='git mv'
alias grm='git rm'
alias gco='git checkout'
alias gb='git branch'
alias gmg='git merge'

# Commitizen
alias czc='cz commit'

# CLI Tools
alias mycli='mycli --myclirc "$XDG_CONFIG_HOME/mycli/config"'
alias weather='curl wttr.in'
alias chatgpt='python3 ~/Developer/chatgpt-cli/chatgpt.py --key=$(python3 ~/Developer/chatgpt-cli/auth-chatgpt-cli.py)'

# Audio
alias sas-airpods='SwitchAudioSource -s "band4band"'
alias sas-speaker='SwitchAudioSource -s "CalDigit TS4 Audio - Rear"'
alias sas-macbook='SwitchAudioSource -s "MacBook Pro Speakers"'
