#!/usr/bin/env bash

# shellcheck disable=SC1091
source "$ZDOTDIR/configs/aliases"
unalias list-fpath
unalias list-highlighter

# Aggregate number of files
alias count-files=count_files

# Outputs PATH
alias list-path='tr ":" "\n" <<< "$PATH"'

# Outputs Shell info
alias list-funcs='declare -F | cut -d " " -f3 | grep -v "/"'
alias list-opts='shopt -p'

# Outputs Terminal colors
alias list-256=ble-color-show
alias list-colors=list_colors

# Update Management
alias update-all='update_all'
alias update-feature-branches='update_feature_branches'
alias update-icons='update_icons'

# Attach to last session, if none then create new one
alias t='tmux attach || tmux new-session'

# Kill and restart all sessions
alias restart-tmux='tmux kill-server &>/dev/null; (tmux attach || tmux new-session ) &>/dev/null'

# Prints all sessions
alias list-tmux-sessions=list_tmux_sessions
