#!/usr/bin/env bash

# TODO fix so reload clears variables from current shell - issue with bind -x
# Reload bash
bind -x '"\C-e": "exec '"$(brew --prefix)"'/bin/bash\n"'

# Clear screen
bind -m vi-insert '"\eL": clear-screen'
bind -m vi-command '"\eL": clear-screen'
