#!/usr/bin/env bash

# Reload bash
bind -x '"\C-o": "exec '"$(brew --prefix)"'/bin/bash"'

# Clear screen
# TODO fix so clear screen works from vim mode
bind -x '"^[l": "clear-screen\n"'

# Atuin search in vim mode
bind -m vi-command '"\C-r": "i__atuin_history\n"'
bind -m vi-command '"\e[A": "i__atuin_history --shell-up-key-binding\n"'
bind -m vi-command '"\eOA": "i__atuin_history --shell-up-key-binding\n"'
