local icons = require 'icons'

require('nvim-web-devicons').setup {
  override = {
    -- Defaults we lean on
    sh = { icon = icons.shell, name = 'sh' },
    bash = { icon = icons.shell, name = 'bash' },
    zsh = { icon = icons.shell, name = 'zsh' },
    default_icon = { icon = icons.file, name = 'Default' },
    js = { icon = icons.javascript, name = 'js' },
    ts = { icon = icons.typescript, name = 'ts' },
    lock = { icon = icons.lock, name = 'lock' },
    ['robots.txt'] = { icon = icons.robot, name = 'robots' },
    ['.gitignore'] = { icon = icons.branch, name = 'git' },
    Makefile = { icon = icons.makefile, name = 'Makefile' },
    txt = { icon = icons.file, name = 'txt' },
    config = { icon = icons.gear, name = 'config' },
    md = { icon = icons.markdown, name = 'md' },

    -- Zsh helpers (autoload + wrappers)
    aliases = { icon = icons.shell, name = 'aliases' },
    ['funcs'] = { icon = icons.shell, name = 'funcs' },
    ['cheatsheet'] = { icon = icons.shell, name = 'cheatsheet' },
    ['commit-and-sync'] = { icon = icons.shell, name = 'commit-and-sync' },
    ['fix-tmux-remotes'] = { icon = icons.shell, name = 'fix-tmux-remotes' },
    ['list-256'] = { icon = icons.shell, name = 'list-256' },
    ['list-colors'] = { icon = icons.shell, name = 'list-colors' },
    ['take'] = { icon = icons.shell, name = 'take' },
    ['update-all'] = { icon = icons.shell, name = 'update-all' },
    ['update-feature-branches'] = { icon = icons.shell, name = 'update-feature-branches' },
    ['update-icons'] = { icon = icons.shell, name = 'update-icons' },
    ['uvi'] = { icon = icons.shell, name = 'uvi' },
    ['work'] = { icon = icons.shell, name = 'work' },

    -- Dotfiles + environment helpers
    ['.dircolors'] = { icon = icons.gear, name = '.dircolors' },
    ['.hushlogin'] = { icon = icons.file, name = '.hushlogin' },
    ['.python-version'] = { icon = icons.gear, name = '.python-version' },
    ['config.sh'] = { icon = icons.gear, name = 'config.sh' },
    ['.bashrc'] = { icon = icons.gear, name = '.bashrc' },
    ['.bash_profile'] = { icon = icons.gear, name = '.bash_profile' },
    ['.zshenv'] = { icon = icons.gear, name = '.zshenv' },
    ['.zshrc'] = { icon = icons.gear, name = '.zshrc' },
    ['.zprofile'] = { icon = icons.gear, name = '.zprofile' },
    ['.env'] = { icon = icons.key, name = '.env' },
    ['bootstrap.sh'] = { icon = icons.sync, name = 'bootstrap.sh' },
    ['.state.itermexport'] = { icon = icons.gear, name = '.state.itermexport' },
    ['.localized'] = { icon = icons.localized, name = '.localized' },
    ['.dbxignore'] = { icon = icons.file, name = '.dbxignore' },
    ['README.md'] = { icon = icons.markdown, name = 'README' },
    ['LICENSE'] = { icon = icons.markdown, name = 'LICENSE' },
    ['CONTRIBUTING.md'] = { icon = icons.markdown, name = 'CONTRIBUTING' },
    ['SECURITY.md'] = { icon = icons.markdown, name = 'SECURITY' },

    -- Generic config formats
    toml = { icon = icons.gear, name = 'toml' },
    yaml = { icon = icons.gear, name = 'yaml' },
    yml = { icon = icons.gear, name = 'yml' },
    xml = { icon = icons.gear, name = 'xml' },

    -- Package / lock manifests
    Brewfile = { icon = icons.package, name = 'Brewfile' },
    ['Brewfile.lock.json'] = { icon = icons.package, name = 'Brewfile.lock' },
    ['package.lock'] = { icon = icons.package, name = 'package.lock' },
    ['package-lock.json'] = { icon = icons.package, name = 'package-lock' },
    ['pnpm-lock.yaml'] = { icon = icons.package, name = 'pnpm-lock' },
    ['yarn.lock'] = { icon = icons.package, name = 'yarn.lock' },
    ['package.json'] = { icon = icons.package, name = 'package.json' },
    ['bun.lockb'] = { icon = icons.package, name = 'bun.lockb' },
    ['uv.lock'] = { icon = icons.lock, name = 'uv.lock' },
    ['requirements.txt'] = { icon = icons.package, name = 'requirements' },
    ['poetry.lock'] = { icon = icons.package, name = 'poetry.lock' },
    Pipfile = { icon = icons.package, name = 'Pipfile' },
    ['Pipfile.lock'] = { icon = icons.package, name = 'Pipfile.lock' },
    ['pyproject.toml'] = { icon = icons.package, name = 'pyproject' },
    ['Cargo.toml'] = { icon = icons.package, name = 'Cargo.toml' },
    ['Cargo.lock'] = { icon = icons.package, name = 'Cargo.lock' },
    ['go.mod'] = { icon = icons.package, name = 'go.mod' },
    ['go.sum'] = { icon = icons.package, name = 'go.sum' },
    Gemfile = { icon = icons.package, name = 'Gemfile' },
    ['Gemfile.lock'] = { icon = icons.package, name = 'Gemfile.lock' },
    ['pom.xml'] = { icon = icons.package, name = 'pom.xml' },
    ['build.gradle'] = { icon = icons.package, name = 'build.gradle' },
    ['build.gradle.kts'] = { icon = icons.package, name = 'build.gradle.kts' },
    ['gradle.lockfile'] = { icon = icons.package, name = 'gradle.lockfile' },
    ['composer.json'] = { icon = icons.package, name = 'composer.json' },
    ['composer.lock'] = { icon = icons.package, name = 'composer.lock' },
    ['mix.exs'] = { icon = icons.package, name = 'mix.exs' },
    ['mix.lock'] = { icon = icons.package, name = 'mix.lock' },
    ['stack.yaml'] = { icon = icons.package, name = 'stack.yaml' },
    ['cabal.project'] = { icon = icons.package, name = 'cabal.project' },
    ['cabal.project.freeze'] = { icon = icons.package, name = 'cabal.project.freeze' },
    ['pubspec.yaml'] = { icon = icons.package, name = 'pubspec.yaml' },
    ['pubspec.lock'] = { icon = icons.package, name = 'pubspec.lock' },
    ['Package.swift'] = { icon = icons.package, name = 'Package.swift' },
    ['Package.resolved'] = { icon = icons.package, name = 'Package.resolved' },
    ['packages.config'] = { icon = icons.package, name = 'packages.config' },
    ['project.assets.json'] = { icon = icons.package, name = 'project.assets' },
    ['nvim-pack-lock.json'] = { icon = icons.package, name = 'nvim-pack-lock', color = '#00c4d8' },
  },
}

require('nvim-tree').setup {
  hijack_cursor = true,
  disable_netrw = true,
  sync_root_with_cwd = true,
  filesystem_watchers = { enable = false },
  view = { preserve_window_proportions = true },
  update_focused_file = { enable = true },
  modified = { enable = true },
  filters = { git_ignored = false },
  live_filter = { prefix = icons.search .. ' ' },
  help = { sort_by = 'desc' },

  diagnostics = {
    enable = true,
    show_on_dirs = true,
    icons = {
      hint = 'H',
      info = 'I',
      warning = 'W',
      error = 'E',
    },
  },

  renderer = {
    root_folder_label = false,
    special_files = { 'README.md' },
    highlight_git = true,
    highlight_diagnostics = true,
    highlight_modified = 'icon',

    indent_markers = {
      enable = true,
      icons = { edge = '┊', item = '┊' },
    },

    icons = {
      modified_placement = 'signcolumn',
      diagnostics_placement = 'before',

      glyphs = {
        modified = icons.modified,

        folder = {
          default = icons.folder,
          empty = '󱧹',
          empty_open = '󰷏',
          open = '󰷏',
          symlink = '󱉆',
        },

        git = {
          renamed = '𝙍',
          staged = '+',
          unmerged = '!',
          unstaged = '~',
          untracked = '?',
          ignored = '',
          deleted = '✘',
        },
      },
    },
  },
}
