return {
	'nvzone/menu',
	'nvzone/volt',
	'rafamadriz/friendly-snippets',
	'stevearc/dressing.nvim',
	'nvim-lua/plenary.nvim',
	'MunifTanjim/nui.nvim',
	'nvim-tree/nvim-web-devicons',
	'zbirenbaum/copilot.lua',
	'saadparwaiz1/cmp_luasnip',
	'hrsh7th/cmp-nvim-lua',
	'hrsh7th/cmp-nvim-lsp',
	'hrsh7th/cmp-buffer',
	'hrsh7th/cmp-path',
	{ 'nvzone/minty', cmd = { 'Huefy', 'Shades' } },
	{ 'tpope/vim-obsession', cmd = 'Obsession' },
}
