#!/usr/bin/env zsh

# -------------------------------- File Editing ---------------------------------------

# Open all files in current directory excluding...
alias va='$EDITOR $(fd -HItf --exclude .git --exclude .github --exclude Session.vim --exclude "Icon?")'

# Fuzzy Search all files in current directory, then open
alias vf='fzf --preview "bat -n --color=always {}" | xargs -r "$EDITOR"'

# Open vim using viminfo state file
alias vi='vim -i "$XDG_STATE_HOME/vim/viminfo"'

# Deletes temp file - NOTE this fixes neovim shada error, but unsure why this works...
alias reload-shada='mv -f "$XDG_STATE_HOME/nvim/shada/main.shada.tmp.x" "$XDG_STATE_HOME/nvim/shada/main.shada"'

# -------------------------------- File Management & Previewing ---------------------------------------

# Move up 2 directories
alias ...="cd ../.."

# uses value of $GREP_COLOR
alias grep='grep --color=auto'

# List all directory items in long format with git info
alias l='eza --all --long --git --icons=always --group-directories-first'

# Print all directory items in colored tree format excluding git info
alias tree='tree -aCI ".git|.github"'

# On Macos merge namespaces of dircolors and gdircolors
[[ $(uname) == Darwin ]] && alias dircolors='gdircolors'

# Deletion
alias delete-ds-store='fd -HI .DS_Store / -x rm -f {} &>/dev/null'

# Fuzzy search man pages
alias docs='compgen -c | fzf | xargs man'

# -------------------------------- List Long Functions ---------------------------------------

# Outputs System info
alias list-sysinfo='system_profiler SPSoftwareDataType SPHardwareDataType'
alias list-shells='tail -n +5 /etc/shells'
alias list-users='dscl . list /Users | grep -v "^_"'

# Outputs Homebrew package info
alias list-deps='brew deps --tree --installed'
alias list-apps='brew list --cask | xargs -n1'
alias list-cmds='brew list --formula | xargs -n1'

# Outputs Aliases & Environment Variables
alias list-alias='alias | sort'
alias list-vars='env | sort'

# Outputs Functions, Options, PATH and FPATH
if [[ -n $ZSH_VERSION ]]; then
  alias list-funcs='print -l ${(ok)functions[(I)[^_]*]} | sort'
  alias list-opts='setopt'
  alias list-path='print -l "${path[@]}"'
  alias list-fpath='print -l ${fpath[@]}'
elif [[ -n $BASH_VERSION ]]; then
  alias list-funcs='declare -F | cut -d " " -f3 | grep -v "/"'
  alias list-opts='shopt -p'
  alias list-path='tr ":" "\n" <<< "$PATH"'
fi

# Outputs syntax-highlighting info
[[ -n $ZSH_HIGHLIGHT_STYLES ]] && alias list-highlighter='print -raC2 - "${(@kvq+)ZSH_HIGHLIGHT_STYLES}" | sort'

# -------------------------------- Workspace Management ---------------------------------------

# Attach to last tmux session, if none then create new one
alias t='tmux attach || tmux new-session'

# Kill and restart all sessions
alias reload-tmux='tmux kill-server &>/dev/null; tmux attach &>/dev/null || tmux new-session &>/dev/null'

# -------------------------------- Version Control ---------------------------------------

# Commitizen
alias czc='cz commit'

# Git
alias gaa='git add --all'
alias gd='git diff'
alias gds='git diff --staged'
alias glg='git log --graph --date=format:"%b-%d-%Y" --pretty="$GIT_PRETTY"'
alias gp='git push'
alias grs='git restore'
alias grst='git restore --staged'
alias grv='git remote --verbose'
alias gst='git status'

alias gsw='git branch --format="%(refname:short)" | fzf --header "git switch" --border-label "  branches " --preview "git show --color=always {1}" | xargs -r git switch'

# -------------------------------- CLI tools ---------------------------------------

# MySQL launcher
alias mycli='mycli --myclirc "$XDG_CONFIG_HOME/mycli/config"'

# Print weather data
alias weather='curl wttr.in'

# AI launcher
alias chatgpt='python ~/Developer/chatgpt-cli/chatgpt.py --key=$(python ~/Developer/chatgpt-cli/auth-chatgpt-cli.py)'

# Sound toggler
alias sas-airpods='SwitchAudioSource -s "band4band"'
alias sas-speaker='SwitchAudioSource -s "CalDigit TS4 Audio - Rear"'
alias sas-macbook='SwitchAudioSource -s "MacBook Pro Speakers"'

# Remove macOS quarantine flag(s)
alias fix-spotify='sudo xattr -rd com.apple.quarantine /Applications/Spotify.app'

# -------------------------------- Suffix Aliases ---------------------------------------

command -v autoload &>/dev/null && autoload -Uz is-at-least && is-at-least 4.2.0 && {
  # Images
  _image_fts=(jpg jpeg png gif mng tiff tif xpm)
  for ft in $_image_fts; do alias -s $ft='open -a Preview'; done

  # Videos
  _media_fts=(ape avi flv m4a mkv mov mp3 mpeg mpg ogg ogm rm wav webm)
  for ft in $_media_fts; do alias -s $ft='open -a VLC'; done

  # Docs
  alias -s pdf='open -a Skim'

  # Compressed
  alias -s zip='unzip -l'
  alias -s tar='tar tf'
  alias -s tar.gz='echo '
}
