#!/usr/bin/env zsh

# Reload zsh
bindkey -s '^o' 'exec "$(brew --prefix)/bin/zsh"\n'

# https://github.com/zsh-users/zsh-autosuggestions?tab=readme-ov-file#key-bindings
bindkey '^e' autosuggest-accept
bindkey '^y' autosuggest-execute

# Zoxide
bindkey -s '^p' 'ji\n'

# Neovim
bindkey -s '^n' '"$EDITOR" -S Session.vim\n'

# Clear screen
bindkey -s '^[l' 'clear\n'

# Atuin search in vim mode
bindkey -M vicmd '^r' atuin-search
bindkey -M vicmd '^[[A' atuin-up-search
bindkey -M vicmd '^[OA' atuin-up-search
