--- @type table<string, string> -- commonly used icons
return {
  modified = '󰷬',

  -- virtual text
  virtualblock = '󱓻',
  virtualcircle = '',

  -- general
  bell = ' ',
  checkmark = '✔',
  dotted_circle = '󱥸 ',
  download = ' ',
  file = '',
  folder = '',
  gear = '',
  branch = '',
  cursor = '󰆾',
  vim = '',
  up = '',
  down = '',
  recent = '',
  search = '',
  fuzzy = '',
  cmd_hist = '',
  git = '',
  log = '',
  status = '󰦒',

  -- lsp diagnostics
  error = '󰯈',
  warn = '',
  hint = '',
  info = '',

  -- devicons
  javascript = '󰌞',
  typescript = '󰛦',
  lock = '',
  robot = '󱙺',

  -- lsp completions
  namespace = '󰌗',
  text = '󰉿',
  method = '󰆧',
  ['function'] = '󰆧',
  constructor = '',
  field = '',
  variable = '󰀫',
  class = '󰠱',
  interface = '',
  module = '',
  property = '󰜢',
  unit = '󰑭',
  value = '󰎠',
  enum = '',
  keyword = '󰌋',
  snippet = '',
  color = '󰏘',
  reference = '󰈇',
  enumMember = '',
  constant = '󰏿',
  struct = '󰙅',
  event = '',
  operator = '󰆕',
  typeparameter = '󰊄',
  table = '',
  object = '󰅩',
  tag = '',
  array = '[]',
  boolean = '',
  number = '',
  null = '󰟢',
  supermaven = '',
  string = '󰉿',
  calendar = '',
  watch = '󰥔',
  package = '',
  copilot = '',
  codeium = '',
  tabnine = '',
  bladenav = '',
}
