#!/usr/bin/env bash

# Load shared aliases from zsh
# shellcheck disable=SC1091
source "$ZDOTDIR/aliases"

# Aggregate number of files
alias count-files=count_files

# Outputs PATH
alias list-path='tr ":" "\n" <<< "$PATH"'

# Outputs Shell info
alias list-funcs='declare -F | cut -d " " -f3 | grep -v "/"'
alias list-opts='shopt -p'

# Outputs Terminal colors
alias list-256=ble-color-show
alias list-colors=list_colors

# Prints all sessions
alias list-tmux-sessions=list_tmux_sessions

# Update Management
alias update-all=update_all
alias update-feature-branches=update_feature_branches
alias update-icons=update_icons
